### PR TITLE
Various fixes for portability and simplification

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Review by digitalronin — CHANGES_REQUESTED** [review]
The use of "makefile" rather than "Makefile" is deliberate - it makes life easier on OSX, with its weird approach to case-sensitivity in filenames.
Please amend the PR to restore 'makefile'

**Comment by rrthomas** [comment]
I've gone one better, and removed it altogether.

**Comment by digitalronin** [comment]
The setup.sh script doesn't work cleanly on a mac unless the user has $HOME/Library/Python/3.7/bin in their path.

**Comment by rrthomas** [comment]
What goes wrong?

**Comment by digitalronin** [comment]
It can't find pipenv, after installing it. If you add that setting to the path, it's fine

**Comment by rrthomas** [comment]
PR #2 fixes this (tested on macOS and Ubuntu).

**Pull request merged**
